environment: app
base_url: gig3r.com

frontend:
  image: ghcr.io/gig3r-com/gig3r-frontend
  tag: 0.2.0

backend:
  image: ghcr.io/gig3r-com/gig3r-backend
  tag: 0.2.0

database:
  name: giger
  user: giger
  password: giger
  image: ghcr.io/gig3r-com/gig3r-postgres
  tag: 0.2.0
